name: CI (PRs/branches)

on:
  push:
    branches-ignore:
      - "root"

  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-XX:MaxMetaspaceSize=5G" >> ~/.gradle/gradle.properties

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v3

        env:
          TOKEN: "${{ secrets.TOKEN }}"

      - name: Gradle (Build)
        run: "./gradlew checkLicenses build"

        env:
          TOKEN: "${{ secrets.TOKEN }}"

      - name: Gradle (Test)
        run: "./gradlew build"
        working-directory: "./testModule"

      - name: Upload plugin JARs
        uses: actions/upload-artifact@v4

        with:
          name: Plugin JARs
          path: "*/build/libs/*.jar"
